### ISSUE TITLE
Training

### ISSUE THREAD

**Issue by Maelstroom** [baldassarreFe/deep-koalarization#10]
Hi,
I am a student in deep learning and neural network.
Could you help me with some questions I wonder myself ?

how many lab_images_*.tfrecord do we need to do before training ?
For val_lab_images_*.tfrecord, do we just need to rename one lab_images_.tfrecord ?
Where are the grey images ?

Cheers

Simon

**Comment by baldassarreFe** [comment]
Hi,

> how many lab_images_.tfrecord do we need to do before training?

Ideally the whole ImageNet, but in practice you can start with ~10,000 or so.

> For val_lab_images_.tfrecord, do we just need to rename one lab_images_.tfrecord ?

Yes, just pick one and rename it.

> Where are the grey images ?

Not sure I understand the question. All images need to have color information for training/validation/testing which is then separated when they are pre-processed.
After training, you can feed a gray image to the network, but that requires a bit of a work-around and it's not included in the repo.
