### ISSUE TITLE
from resizeimage import resizeimage

### ISSUE THREAD

**Issue by Flyzzz** [baldassarreFe/deep-koalarization#14]
I con't find the model resizeimage .

**Comment by baldassarreFe** [comment]
It's an external dependency to [python-resize-image](https://pypi.org/project/python-resize-image/) listed in [requirements.txt](https://github.com/baldassarreFe/deep-koalarization/blob/b6a4c7af31e80436c562d6ed456c1cbbc853014f/requirements.txt#L18).

All dependencies get installed when you do `pip install -r requirements.txt`.
