### ISSUE TITLE
TypeError: Can not convert a LabImageRecordReader into a Tensor or Operation.

### ISSUE THREAD

**Issue by youyingyin** [baldassarreFe/deep-koalarization#4]
TypeError: Fetch argument <dataset.tfrecords.images.lab_image_record.LabImageRecordReader object at 0x0000000074CF3940> has invalid type <class 'dataset.tfrecords.images.lab_image_record.LabImageRecordReader'>, must be a string or Tensor. (Can not convert a LabImageRecordReader into a Tensor or Operation.)

i got this error when i ran train.py.

# **the solution is below@charleshamesse  .check it out**

**Comment by artemik** [comment]
I get the same error.

**Comment by matheusbarrosp** [comment]
I get the same error. [2]

**Comment by charleshamesse** [comment]
I fixed it by editing the `training_pipeline`'s return statement in `colorization.training_utils`. Remove `irr` and `read_batched_examples` on line 50:
```
return {
        'global_step': global_step,
        'optimizer': optimizer,
        'cost': cost,
        'summary': summary
    } #, irr, read_batched_examples
```
